Sistema3de3/Controllers/ControlController.cs


using Rotativa;
/**
* Sistema 3 de 3 para Gobierno del Estado de Jalisco
*
* Desarrollado por Nicotina Estudio
* http://www.nicotinaestudio.com - hola@nicotinaestudio.mx
*
* Creado por: Carlos Isaac Hernández Morfín.
* Fecha de creación: 18/01/2017
**/
using Sistema3de3.DAL;
using Sistema3de3.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Sistema3de3.Controllers
{
    public class ControlController : Controller
    {
        private S3Context db = new S3Context();

        public ActionResult Index()
        {
            return View();
        }

        #region MÓDULO 2.1

        public ActionResult Modulo2_1()
        {
            return View();
        }

        public ActionResult Administradores()
        {
            return View(db.Usuarios.ToList());
        }

        public ActionResult AgregarAdministrador()
        {
            ViewBag.EntidadId = new SelectList(db.Entidades, "EntidadId", "Nombre");
            ViewBag.UnidadResponsableId = new SelectList(db.UnidadesResponsables, "UnidadResponsableId", "Nombre");
            ViewBag.CargoId = new SelectList(db.Cargos, "CargoId", "Nombre");

            return View();
        }

        [HttpPost]
        public ActionResult AgregarAdministrador(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Usuarios.Add(usuario);
                    db.SaveChanges();

                    return RedirectToAction("Administradores");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Ocurrio un error en el servidor, por favor inténtalo más tarde.");
                    return View();
                }
            }

            return View();
        }

        public ActionResult Reportes()
        {
            return View(db.ServidoresPublicos.ToList());
        }

        public ActionResult Exportar()
        {
            return new ActionAsPdf("GeneratePDF");
        }

        public ActionResult GeneratePDF()
        {
            var data = db.ServidoresPublicos.ToList();
            return View("Reportes", data);
        }

        public ActionResult Catalogos()
        {
            return View();
        }
        #endregion
    }
}

Sistema3de3/Controllers/PresentacionController.cs


using Sistema3de3.DAL;
/**
* Sistema 3 de 3 para Gobierno del Estado de Jalisco
*
* Desarrollado por Nicotina Estudio
* http://www.nicotinaestudio.com - hola@nicotinaestudio.mx
*
* Creado por: Carlos Isaac Hernández Morfín.
* Fecha de creación: 18/01/2017
**/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sistema3de3.Controllers
{
    public class PresentacionController : Controller
    {
        private S3Context db = new S3Context();

        public ActionResult Index(int? id)
        {
            var idx = id;

            if(id == null)
                idx = db.ServidoresPublicos.FirstOrDefault().UsuarioId;

            return View(db.ServidoresPublicos.Find(idx));
        }

        public ActionResult DeclaracionesPendientes(int id)
        {
            return View(db.ServidoresPublicos.Find(id));
        }

        public ActionResult EditarDeclaracion(int id)
        {
            return View(db.Declaraciones.Find(id));
        }

        public ActionResult Patrimoniales()
        {
            return View();
        }
    }
}

Sistema3de3/Controllers/RegistroController.cs
using Sistema3de3.DAL;
using Sistema3de3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sistema3de3.Controllers
{
    public class RegistroController : Controller
    {
        private S3Context db = new S3Context();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ServidoresPublicos()
        {
            return View(db.ServidoresPublicos.ToList());
        }

        public ActionResult AgregarServidor()
        {
            ViewBag.EntidadId = new SelectList(db.Entidades, "EntidadId", "Nombre");
            ViewBag.UnidadResponsableId = new SelectList(db.UnidadesResponsables, "UnidadResponsableId", "Nombre");
            ViewBag.CargoId = new SelectList(db.Cargos, "CargoId", "Nombre");

            return View();
        }

        [HttpPost]
        public ActionResult AgregarServidor(ServidorPublico usuario)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.ServidoresPublicos.Add(usuario);
                    db.SaveChanges();

                    return RedirectToAction("ServidoresPublicos");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Ocurrio un error en el servidor, por favor inténtalo más tarde.");
                    return View();
                }
            }

            return View();
        }


        public ActionResult EditarServidorPublico(int id)
        {
            ViewBag.EntidadId = new SelectList(db.Entidades, "EntidadId", "Nombre");
            ViewBag.UnidadResponsableId = new SelectList(db.UnidadesResponsables, "UnidadResponsableId", "Nombre");
            ViewBag.CargoId = new SelectList(db.Cargos, "CargoId", "Nombre");

            return View(db.ServidoresPublicos.Find(id));
        }


        public ActionResult DetalleServidorPublico(int id)
        {
            return View(db.ServidoresPublicos.Find(id));
        }


        public ActionResult AgregarObligacion()
        {
            ViewBag.UsuarioId = new SelectList(db.ServidoresPublicos, "UsuarioId", "RFC");

            return View();
        }

        [HttpPost]
        public ActionResult AgregarObligacion(Declaracion declaracion)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var serv = db.ServidoresPublicos.Find(declaracion.UsuarioId);

                    serv.Declaraciones.Add(declaracion);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Ocurrio un error en el servidor, por favor inténtalo más tarde.");
                    return View();
                }
            }

            return View();
        }
    }
}

Sistema3de3/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
 
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema 3 de 3</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/"><img id="logo" src="~/Content/Imagenes/logo-3-de-3-blanco.png" /></a>
            </div>
            <div class="navbar-collapse collapse">

@if (Request.IsAuthenticated)
{
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Módulo 1", "Index", "Presentacion")</li>
                    <li>@Html.ActionLink("Módulo 2", "Index", "Control")</li>
                    <li>@Html.ActionLink("Módulo 3", "Index", "Registro")</li>
                </ul>
}
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
    </div>
    <footer>
        <img src="~/Content/Imagenes/logo-contraloria.png" />
        <p>Mapa del sitio | Políticas de uso y privacidad | Acerca de este portal | Contacto</p>
        <p>Gobierno del Estado de Jalisco , algunos derechos reservados  &copy; @DateTime.Now.Year - Sistema 3 de 3 por: <a href="http://www.nicotinaestudio.com" target="_blank">Nicotina Estudio</a></p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>